Yosabet plant
dev-mission/gardenspace pull request #6
Opened 2021-04-22 04:02 UTC by YosabetK

2021-04-22 04:09 UTC, Chronowork1 approved these changes

2021-04-29 02:20 UTC, francisli requested changes

2021-04-29 02:20 UTC, francisli commented on migrations/20210422022213-create-profile.js
> +      userId: {
Foreign keys should be CamelCase capitalized...  UserId not userId ...

2021-04-29 02:20 UTC, francisli commented on migrations/20210422022213-create-profile.js
> +      descrption: {
Typo: description

2021-04-29 02:20 UTC, francisli commented on migrations/20210422022213-create-profile.js
> +        type: Sequelize.INTEGER
Phone numbers, stored as STRING

2021-04-29 02:20 UTC, francisli commented on migrations/20210422022213-create-profile.js
> +      phonenumber: {
Recommend: phoneNumber

2021-04-29 02:20 UTC, francisli commented on models/attendees.js
> +  class Attendees extends Model {
The model class name should be singular Attendee, not plural Attendees

2021-04-29 02:20 UTC, francisli commented on models/attendees.js
> +  Attendees.init({
Singular

2021-04-29 02:20 UTC, francisli commented on models/attendees.js
> +    phoneNumber: DataTypes.INTEGER,
Use STRING

2021-04-29 02:20 UTC, francisli commented on models/attendees.js
> +    modelName: 'Attendees',
Singular

2021-04-29 02:20 UTC, francisli commented on models/attendees.js
> +  return Attendees;
Singular

2021-04-29 02:20 UTC, francisli commented on models/attendees.js
> +'use strict';
Please rename this file from models/attendees.js to models/attendee.js so that the filename is singular as well.

2021-04-29 04:20 UTC, merged